version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - db_data:/app/sqlite
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=sqlite:///sqlite.db
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - db_data:/data

volumes:
  db_data:
